services:
  my-app-development:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build:
      context: ../../
    image: my-app-development
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file: "../../.env.development.sample"
    volumes:
      - ../..:/app # mount local source code into container
    networks:
      - my_network
    command: sh -c "npm run migration:run && npm run dev"

  db:
    image: postgres:latest
    env_file: "../../.env.development.sample"
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - my_network


volumes:
  postgres_data:

networks:
  my_network:
    name: my_network
    driver: bridge
